### ISSUE TITLE
การพัฒนาแอพ Phase ที่ 1

### ISSUE THREAD

**Issue by mildronize** [TechNukrom/technukrom#2]
## เป้าหมาย
**Tech นุกรม** = ศูนย์กลางความรู้สำหรับนักพัฒนา ( developer) โดยที่เน้นภาษาไทยเป็นหลัก (ถ้ามี)
เน้นเรื่องของ personalization เป็น ล็อกอินเข้ามาเพื่ออ่านในสิ่งที่เราสนใจ

## กลุ่มเนื้อหา
- News
- Blogs 
- Awesome
- Cheat sheet
- Documents
- Knowledge & books
- Video

## Technology Stack
- **Hosting**: [https://zeit.co/now](https://zeit.co/now) @ [Technukrom](https://technukrom.now.sh/)
- **Frontend Framework**: [Nextjs](https://nextjs.org/)
- **DB & Backend**: Firestone by Firebase

# Need Help
- [ ] แหล่งข้อมูลภาษาไทย ทุกที่
- [ ] Logo design
- [ ] การออกแบบหน้าเว็บหลัก
- [ ] ค่า Domain 
- [ ] ค่า Hosting (อาจจะมีในอนาคต ถ้าระบบใหญ่มากกว่านี้)

**Comment by mildronize** [comment]
## TODO
- [X] อ่านข้อมูลจาก Firestore ได้
- [X] เขียนตัว data crawler เข้าสู่ db 
- [ ] เขียน Readme
- [ ] เขียน Doc
- [ ] ทำ SEO

## maintain
- dir structure
- naming
- refactor component
- linting & prettier
- postCSS for consistency var


## Featured
- [ ] page URL # สำหรับ ให้ back  กลับมาตำแหน่งเดิมได้
- [ ] ga
- [ ] link count
